name: Maven Tests with Allure

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'

      # Ensure Chrome exists so Selenium Manager picks a matching driver
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run tests (headless, no shared profile)
        env:
          CI: "true"
          HEADLESS: "true"
          CHROME_USER_DATA_DIR: ""
          XDG_CONFIG_HOME: ""
          XDG_RUNTIME_DIR: ""
        run: mvn -B clean test

      - name: Generate Allure Report
        if: always()
        run: mvn -B allure:report

      - name: Publish Allure to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/site/allure-maven-plugin
