name: Maven Tests with Allure

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Set up Java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'

      # 3️⃣ Set up Chrome for Selenium
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      # 4️⃣ Set up Node.js (for Allure CLI)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 5️⃣ Install Allure CLI globally
      - name: Install Allure CLI
        run: |
          npm i -g allure-commandline@latest --no-audit --no-fund
          allure --version

      # 6️⃣ Run Maven tests (headless mode)
      - name: Run tests
        env:
          CI: "true"
          HEADLESS: "true"
          CHROME_USER_DATA_DIR: ""
          XDG_CONFIG_HOME: ""
          XDG_RUNTIME_DIR: ""
        run: mvn -B clean test

      # 7️⃣ Generate Allure Report in root directory
      - name: Generate Allure Report in root
        if: always()
        run: allure generate allure-results --clean -o allure-report

      # 8️⃣ Publish Allure Report to GitHub Pages
      - name: Publish Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

      # 9️⃣ Send Allure Report Link via Email (SMTP2GO)
      - name: Email Allure Report Link
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.smtp2go.com    # ✅ Correct key
          server_port: 587                    # ✅ Correct key
          secure: false                       # 587 = STARTTLS
          username: ${{ secrets.SMTP2GO_QA_TEST }}
          password: ${{ secrets.SMTP2GO_RELEASE_PASSWORD }}
          subject: "Allure Report • cucumber_loginpage_framework • Run #${{ github.run_number }} (${{ job.status }})"
          from: "CI Bot <ci@yourdomain.com>"
          to: "cmpnproj2016@gmail.com"
          html_body: |
            <h3>✅ Maven Tests with Allure</h3>
            <p><b>Repository:</b> ${{ github.repository }}</p>
            <p><b>Run Number:</b> ${{ github.run_number }}</p>
            <p><b>Status:</b> ${{ job.status }}</p>
            <p>📊 <a href="https://manasivd030.github.io/cucumber_loginpage_framework/" target="_blank">
              Click here to view the Allure Report
            </a></p>
            <p>Triggered by: ${{ github.actor }}</p>
