name: Maven Tests with Allure

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'

      # Install Chrome for Selenium
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run tests
        env:
          CI: "true"
          HEADLESS: "true"
          CHROME_USER_DATA_DIR: ""
          XDG_CONFIG_HOME: ""
          XDG_RUNTIME_DIR: ""
        run: mvn -B clean test

      - name: Generate Allure Report in root directory
        if: always()
        run: allure serve allure-results

      - name: Publish Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
